import pdb
from models.city import City
from models.country import Country
import repositories.city_repository as city_repository
import repositories.country_repository as country_repository

country_repository.delete_all()
city_repository.delete_all()

country1 = Country("Poland", "Top 10", True, 1)
country_repository.save(country1)
country2 = Country("United Kingdom", "Top 20", True, 2)
country_repository.save(country2)
country3 = Country("France", "Top 50", True, 3)
country_repository.save(country3)
country4 = Country("Germany", "Top 5", True, 4)
country_repository.save(country4)
country5 = Country("Italy", "Top 3", True, 5)
country_repository.save(country5)
country6 = Country("Japan", "Top 4", False, 6)
country_repository.save(country6)
country7 = Country("Florida", "Top 9", False, 7)
country_repository.save(country7)
country8 = Country("Sweden", "Top 60", False, 8)
country_repository.save(country8)
country9 = Country("Egypt", "Top 15", False, 9)
country_repository.save(country9)
country10 = Country("Lebanon", "Top 25", False, 10)
country_repository.save(country10)

city1 = City("Wroclaw", country1)
city_repository.save(city1)
city2 = City("Krakow", country1)
city_repository.save(city2)
city3 = City("Manchester", country2)
city_repository.save(city3)
city4 = City("Livingston", country2)
city_repository.save(city4)
city5 = City("Paris", country3)
city_repository.save(city5)
city6 = City("Nice", country3)
city_repository.save(city6)
city7 = City("Frankfurt", country4)
city_repository.save(city7)
city8 = City("Berlin", country4)
city_repository.save(city8)
city9 = City("Milan", country5)
city_repository.save(city9)
city10 = City("Rome", country5)
city_repository.save(city10)
city11 = City("Tokyo", country6)
city_repository.save(city11)
city12 = City("Kyoto", country6)
city_repository.save(city12)
city13 = City("Jacksonville", country7)
city_repository.save(city13)
city14 = City("Miami", country7)
city_repository.save(city14)
city15 = City("Stockholm", country8)
city_repository.save(city15)
city16 = City("Gothemburg", country8)
city_repository.save(city16)
city17 = City("Alexandria", country9)
city_repository.save(city17)
city18 = City("Cairo", country9)
city_repository.save(city18)
city19 = City("Beirut", country10)
city_repository.save(city19)
city20 = City("Baalbek", country10)
city_repository.save(city20)


pdb.set_trace()